---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: registry.home.devmem.ru/gia-api/python
    registry: registry.home.devmem.ru
    tags:
    - latest
